#!/bin/bash
python3 -m py_compile "$PYFILE"
mv "__pycache__/"$(basename "$PYFILE" .py).cpython-*.pyc "${PYFILE}c" 2>/dev/null || python3 -c "import py_compile; py_compile.compile('$PYFILE', cfile='${PYFILE}c')"
